### ISSUE TITLE
theme the sidebar

### ISSUE THREAD

**Issue by bricewge** [mr-islam/zen-fox#1]
At the moment the sidebar isn't themed, it looks out of place. It is not currently possible to do this, but when https://bugzilla.mozilla.org/show_bug.cgi?id=1418602 will be fixed it will be nice to theme the sidebar.

**Comment by mr-islam** [comment]
@bricewge Yup definitely, this is something other users have suggested also; should be just a one-liner to add once the FF team implements that :smile:

**Comment by mr-islam** [comment]
Latest release now themes sidebar (and much more!) 

@bricewge
