### ISSUE TITLE
Theme resets after switching tabs

### ISSUE THREAD

**Issue by jc00ke** [mr-islam/zen-fox#13]
First off, thanks for making zen fox! It looks great.

The screen capture might be a little confusing, but you can see that I enable the theme and then when I switch tabs the theme is deactivated. This happens when I'm going from a container to the same container, or to another container.

I haven't tried it on vanilla FF, as I'm using FF Dev Edition 65.0b7. Let me know if that would be helpful.

Thanks again!

![zen-fox](https://user-images.githubusercontent.com/18191/50647271-05fe2f00-0f2d-11e9-9ecf-9b4e6a6169e1.gif)

**Comment by mr-islam** [comment]
Thanks for reporting this @jc00ke! The screen capture does seem puzzling. 

If you don't mind, could you please go to `about:debugging` and click the "debug" button below the ZenFox entry (allow the server connection when prompted). Then kindly re-create this bug, and then post the entire log from that console window?

Thanks!

**Comment by jc00ke** [comment]
![image](https://user-images.githubusercontent.com/18191/50673970-0f23e600-0f97-11e9-88fb-771899887a4c.png)
OK, here we go!

I started up the debugger, enabled the theme (`theme: lightapplied`) then immediately I saw the 3 errors. When I switched tabs, the theme did not persist but I didn't see any errors either. I then reapplied the theme (with the ying-yang extension button) and saw `theme: darkapplied` and the same 3 errors.

I'll try it in vanilla FF now.

UPDATE: Yeah, so I don't see this issue in vanilla FF 64.0. I'm not sure what FF dev edition is doing differently.

**Comment by mr-islam** [comment]
Definitely seems like they changed something, probably theming syntax (based on the error messages). 

Thanks for being so helpful @jc00ke! I don't use the dev edition so I wouldn't have noticed this until it got to release (and it messed up for everyone). 

I'm traveling today and school starts tomorrow (😑) so I might take a few days to publish the update though.

**Comment by jc00ke** [comment]
Interesting... so in FF 64, if I start it up with the `GTK_THEME` ENV var set then I get this theme-switching issue. If I start it up without that ENV var set, the theme works correctly. I set the ENV var because FF has an issue with dark themes and certain inputs (I'll snap a screenshot in a sec)

**Comment by jc00ke** [comment]
![image](https://user-images.githubusercontent.com/18191/50732164-f0098d80-1129-11e9-9881-4214613a913f.png)
[WhatsApp Web](https://web.whatsapp.com/) is an example of a "broken" input when I don't set `GTK_THEME=Adwaita` when launching FF. It should have a normal white background.

**Comment by mr-islam** [comment]
@jc00ke I just tried out FF 65.0b8 on Windows and I can confirm getting the same errors in the console log. But, I don't have the same bug where the theme resets on changing to a new tab — the extension is running fine for me.

It's probably the ENV variables and some issue specific to FF on Linux, and if that's the case sadly I won't be able to help beyond this (I don't have Linux installed on my new laptop and I don't want the worry of doing it again!)… I'm really sorry, but I'll try to see if I can find the issue!

**Comment by jc00ke** [comment]
No worries! I'm seeing the theme switch when I use FF's default themes now (dark will revert to light in the same fashion) so it's likely a larger issue. I'll have to see if I can find a bug report in FF.

Thanks, and hopefully they can get the bug fixed so I can enjoy your extension :wink:
