### ISSUE TITLE
Background of browser does not change according to them

### ISSUE THREAD

**Issue by oli666** [mr-islam/zen-fox#14]
Hi,

it seems that only the menu bar gets affected when using either the dark or the light solarized theme. the actual web browser window seems to be not affected. 

![image](https://user-images.githubusercontent.com/7488029/53427161-b4cc6200-39e8-11e9-87be-bedbc2aaf240.png)

**Comment by mr-islam** [comment]
Hi @oli666, that is actually the intended behavior—Zen Fox only themes the Firefox browser itself, and not the web pages you open.

I'm sorry if it was misleading!

**Comment by oli666** [comment]
Hi – thanks for clarifying! I was just confused because on https://addons.mozilla.org/en-US/firefox/addon/zen-fox/ there are two screenshots showing the browser pages in both, light and dark solarized ;)

**Comment by mr-islam** [comment]
Yes—I think I should edit that and mention that the dark/light mode of the website is actually a feature of Reddit, the website in the screenshots.

For that kind of website theming see [Dark Reader](https://darkreader.org/) or [UserStyles](https://userstyles.org/)
