### ISSUE TITLE
Feature req: Chose custom theme for dark mode, and a different custom theme for light mode

### ISSUE THREAD

**Issue by Richard87** [mr-islam/zen-fox#19]
Hi!

I would love to specify my own dark-mode theme (I'm a big fan of Nord Polar Dark)... 

I have no idea if it's even possible for an extension to list installed themes and controll them

**Comment by mr-islam** [comment]
Hi there, thank you for your feedback 🙂

Of course, offering more choices in themes would be possible - it would be really cool to have all the popular colorschemes from code editors available for Firefox too.

But I unfortunately don't have the time to work on that...

If someone else would like to make PRs to add more themes and needed changes to the settings page, I'd be happy to accept them 👍

**Comment by Richard87** [comment]
Thanks for the quick reply, I'll take a look :D

**Comment by mr-islam** [comment]
Awesome! The codebase is quite ugly (to be fair, I wrote it a few years back as a learning experiment) so I hope it's not to painful to go through it 😓

**Comment by Richard87** [comment]
The codebase is extremely nice actually, very easy to navigate and read!

I found a way to list all available extensions, but I can't find a way to override the active theme id :/ 
https://discourse.mozilla.org/t/add-the-possibility-to-modify-extensions-activethemeid-either-as-a-webextension-expirment-or-under-browser-theme/80101

I'll create a pull-request if it ever is possible, but I'm guessing that won't happen anytime soon

```js
async function restoreOptions() {
  var lightThemeSelector = document.querySelector("#lightTheme")
  var darkThemeSelector = document.querySelector("#darkTheme")
  var extensions = await browser.management.getAll();
  var themes = extensions.filter(ext => ext.type === "theme");

  themes.forEach(t => {
    var opt = document.createElement("option");
    opt.value = t.id
    opt.textContent = t.name
    darkThemeSelector.appendChild(opt)
    lightThemeSelector.appendChild(opt.cloneNode(true))
  })

  var config = await browser.storage.local.get()
  document.querySelector("#method").value = config["method"] || 'manual';
  document.querySelector("#hourStart").value = config["hourStart"];
  document.querySelector("#hourEnd").value = config["hourEnd"];
  document.querySelector("#apiKey").value = config["apiKey"];
  document.querySelector("#lat").value = config["lat"];
  document.querySelector("#long").value = config["long"]

  lightThemeSelector.value = config["lightTheme"] || 'firefox-compact-light@mozilla.org';
  darkThemeSelector.value = config["darkTheme"] || 'firefox-compact-dark@mozilla.org';
}
```

**Comment by Richard87** [comment]
Alright, I was wrong, and it works!
![image](https://user-images.githubusercontent.com/5749715/118131117-64d9ea00-b3fe-11eb-909e-d283c92b9fd3.png)

Modified this code as well :) 
```js
async function setTheme(theme) {
  try {
    browser.storage.local.set({'currentTheme': theme});
    var targetTheme = theme === "light" ? "lightTheme" : "darkTheme";
    var themeId = await browser.storage.local.get().then(res => res[targetTheme])

    console.log(`theme: ${theme} (${themeId}) applied`, theme);
    if (themeId === "Solarized") {
      browser.theme.update(themes[theme]);
    } else {
      await browser.management.setEnabled(themeId, true)
    }
  } catch (e) {
    console.warn("Could not set them!", e, theme, themeId)
  }
}

```
