### ISSUE TITLE
settings can't be saved

### ISSUE THREAD

**Issue by bricewge** [mr-islam/zen-fox#2]
With Firefox Nightly 61.0a1 I can't manage to save my settings. Going back to the addon settings after modifying them show it empty.

Related to this, when Firefox start the theme isn't applied, I have to click on the button to apply it.

**Comment by mr-islam** [comment]
With regard to saving settings: I am working on that right now! School is really taking up a lot of my time, and I am just learning the localStorage APIs and stuff, so it's taking longer than it should. Should be able to complete and test it in the next 2 weeks, God willing. See branch `save-settings` for the work-in-progress!

(and I'm making a separate issue for having to apply the theme on startup)

**Comment by bricewge** [comment]
Your last commit on master seems to fix it. It will be nice to have a default settings by though, currently all the options are empty by default. The other add-ons have a default.

**Comment by mr-islam** [comment]
What would you suggest should be default settings, @bricewge? My thinking:

    Method: Manual
    Accents: magenta (light), cyan (dark)

And the rest is *truly* user preference I think (time, location, API key)

**Comment by bricewge** [comment]
It's fine with me.

**Comment by mr-islam** [comment]
As mentioned above, saving works now. Default settings for accents and method are set up now as well.

Final testing to go before releasing the update
