### ISSUE TITLE
Extension does not remember accent color upon restart

### ISSUE THREAD

**Issue by cicervlvs** [mr-islam/zen-fox#22]
Whenever I open Firefox (currently 101.0) on either Windows or Linux, accent color for light mode is default (magenta) despite having it changed to orange previously and despite settings page showing the orange option as currently selected. Then I have to click `Save Settings` to make it go back to orange.

**Comment by mr-islam** [comment]
Thank you for reporting this, this was not a problem in the past so something must have changed in Firefox

Would really appreciate it if you are anyone else with some time could help fix this, shouldn't be too hard

unfortunately I don't have time, or actively use Firefox anymore

**Comment by cicervlvs** [comment]
Somehow fixed it by reinstalling.

**Comment by mr-islam** [comment]
Thank you for letting us know! Did you reinstall Firefox, or the extension?

**Comment by cicervlvs** [comment]
Just the extension, after tinkering with it for a while I realized I only had to delete it and install it again!
