### ISSUE TITLE
new windows aren't themed

### ISSUE THREAD

**Issue by bricewge** [mr-islam/zen-fox#7]
When new windows are created they are not themed by `zen-fox` even though the older windows are.
Adding a listener to [`browse.windows.onCreated`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/onCreated) should fix this.

**Comment by mr-islam** [comment]
That's odd… I just tried that using `Ctrl+N`, right click on link and 'open in new window', and also just starting another instance of Firefox from my desktop — every time, the new window was themed the same as the original window (so `zen-fox` was working). Changing the theme with the toolbar button on one window also changes it on the windows, so it seems to be working well

I'm testing on Firefox Dev Edition (61) — are you on the stable version of Firefox (60)? And I don't think OS would impact this…

**Comment by bricewge** [comment]
Ok I see. The bug is only trigger when using a [lightweight theme](https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes) other than the default one, `Dark` per example.

It's fixed by using the default theme, then `zen-fox` is correctly applied to new windows.
